### ISSUE TITLE
not 6 hours anymore?

### ISSUE THREAD

**Issue by gunmaster42** [Riripii/freeRDP2#4]
Hey this does not appears to be working for more than 40-50 mins now? earlier it use to work for exactly 6 hours but now not more than 1 hour.. whats wrong? :(

**Comment by Riripii** [comment]
maybe it's wrong to be in your ngrok token🤔

**Comment by Riripii** [comment]
I'll check again later, thank you for using it, we'll fix it if the script has an error

**Comment by Riripii** [comment]
there are no more entries, so I closed it

**Comment by gunmaster42** [comment]
okay but RDP is still not working for more than 1 hour :)
