### ISSUE TITLE
 NGROK_AUTH_TOKEN

### ISSUE THREAD

**Issue by ausmadiwala45555** [Riripii/freeRDP2#5]
1x3NsxNM1dF21IxdSGuAvUMarx4_6wXTAdDaDPFnwsHZ3sW2R

**Comment by Riripii** [comment]
don't send tokens in issues, you can fork this repository, and you press the add secret button in the md readme

jangan kirim token dalam masalah, Anda dapat mem-fork repositori ini, dan Anda bisa menekan tombol add secret di readme md
